library(ggplot2)
library(RColorBrewer)
cols = c(brewer.pal(5, "Blues")[2:5], brewer.pal(5, "Greens")[2:5])
cols
library(cowplot)
dat = read.csv("all_history.csv", head=F)
head(dat)
colnames(dat) = c("epoch","train_loss","train_accuracy","test_loss","test_accuracy","number_of_samples","number_of_species","divergence","polymorphism")
head(dat)
dat$samples_per_species = dat$samples/dat$number_of_species
tail(dat)
dat$samples_per_species = dat$number_of_samples/dat$number_of_species
tail(dat)
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(sample_perspecies, divergence, polymorphism), group=interaction(sample_perspecies, divergence, polymorphism)) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=2, alpha=0.8) + facet_wrap(~number_of_samples)
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(sample_perspecies, divergence, polymorphism), group=interaction(sample_perspecies, divergence, polymorphism))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=2, alpha=0.8) + facet_wrap(~number_of_samples)
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(sample_per_species, divergence, polymorphism), group=interaction(sample_per_species, divergence, polymorphism))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=2, alpha=0.8) + facet_wrap(~number_of_samples)
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(samples_per_species, divergence, polymorphism), group=interaction(samples_per_species, divergence, polymorphism))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=2, alpha=0.8) + facet_wrap(~number_of_samples)
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(samples_per_species, divergence, polymorphism), group=interaction(samples_per_species, divergence, polymorphism))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=2, alpha=0.8) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="")
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(divergence, polymorphism, samples_per_species), group=interaction(divergence, polymorphism, samples_per_species))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=2, alpha=0.8) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="")
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(divergence, polymorphism, samples_per_species), group=interaction(divergence, polymorphism, samples_per_species))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="") + xlim(0,200)
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(divergence, polymorphism, samples_per_species), group=interaction(divergence, polymorphism, samples_per_species))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="") + xlim(0,200) + scale_y_continuous(breaks=seq(0,1,0.1)) + background_grid(major="y")
?interaction
ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(divergence, polymorphism, samples_per_species, sep=", "), group=interaction(divergence, polymorphism, samples_per_species, sep=", "))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="") + xlim(0,200) + scale_y_continuous(breaks=seq(0,1,0.1)) + background_grid(major="y")
p1 = ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(divergence, polymorphism, samples_per_species, sep=", "), group=interaction(divergence, polymorphism, samples_per_species, sep=", "))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="") + xlim(0,200) + scale_y_continuous(breaks=seq(0,1,0.1)) + background_grid(major="y")
p2 = ggplot(dat, aes(x=epoch, y=test_accuracy, color=interaction(divergence, polymorphism, samples_per_species, sep=", "), group=interaction(divergence, polymorphism, samples_per_species, sep=", "))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="") + xlim(0,200) + scale_y_continuous(breaks=seq(0,1,0.1)) + background_grid(major="y")
plot_grid(p1, p2, nrow=2)
p2 = ggplot(dat, aes(x=epoch, y=test_accuracy, color=interaction(divergence, polymorphism, samples_per_species, sep=", "), group=interaction(divergence, polymorphism, samples_per_species, sep=", "))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="div, poly, seqs_per_sp") + xlim(0,200) + scale_y_continuous(expand=expand(0,0), breaks=seq(0,1,0.1)) + background_grid(major="y")
p2 = ggplot(dat, aes(x=epoch, y=test_accuracy, color=interaction(divergence, polymorphism, samples_per_species, sep=", "), group=interaction(divergence, polymorphism, samples_per_species, sep=", "))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="div, poly, seqs_per_sp") + xlim(0,200) + scale_y_continuous(expand=c(0,0), breaks=seq(0,1,0.1)) + background_grid(major="y")
p1 = ggplot(dat, aes(x=epoch, y=train_accuracy, color=interaction(divergence, polymorphism, samples_per_species, sep=", "), group=interaction(divergence, polymorphism, samples_per_species, sep=", "))) + geom_point(alpha=0.3) + geom_smooth(span=0.2, se=FALSE, size=0.5, alpha=0.5) + facet_wrap(~number_of_samples) + scale_color_manual(values=cols, name="div, poly, seqs_per_sp") + xlim(0,200) + scale_y_continuous(expand=c(0,0), breaks=seq(0,1,0.1)) + background_grid(major="y")
plot_grid(p1, p2, nrow=2)
plot_grid(p1 + ggtitle("training"), p2 + ggtitle("testing"), nrow=2)
ggsave(file="../../simulations_training_testing_accuracy.png")
savehistory("simulation_plotting.R")
